### ISSUE TITLE
Please stop recommending vultr, they won't unblock port 25 anymore.

### ISSUE THREAD

**Issue by 258204** [LukeSmithxyz/emailwiz#172] opened 2021-10-05 21:25 UTC
Just had an exchange with vultr customer support. I explained I was hosting a mail server for my personal use and they said they couldn't unblock port 25 for me, and linked me to their TOS.

**Comment by LukeSmithxyz** [comment] 2021-10-05 21:32
Show us screencaps. What else have you used Vultr for? Is there anything irregular about your account?

If they won't unblock 25 for you, you'd be the first failure among thousands.

**Comment by 258204** [comment] 2021-10-05 22:27
I set up vultr specifically for your guide on setting up a website, mailserver, and git server. That is all (though I haven't finished setting up the git server). 
![1](https://user-images.githubusercontent.com/71364336/136111423-e76aa392-ceb3-4916-9076-8a38d587c411.png)
![2](https://user-images.githubusercontent.com/71364336/136111425-534e0264-07ec-4c82-98cd-69d1e057a466.png)
![3](https://user-images.githubusercontent.com/71364336/136111428-513aa01a-3650-4219-b52c-e6c396734c97.png)

**Comment by LukeSmithxyz** [comment] 2021-10-06 15:05
Looks like you're talking to a robot. What was in your initial ticket that made it think you were using it for commercial mail?

There is nothing in the terms of service that say they don't do email anymore. It still says they will open up 25 and others.

**Comment by 258204** [comment] 2021-10-20 16:37
Update, they deleted my account, removed the sign up credit from my account, charged the server time from my deposit before returning it.

ie. Instead of giving me a refund, they withdrew the promotional credit. I had to issue a charge-back.

**Comment by javiDev8** [comment] 2021-12-10 01:06
I'm having, the same issue, and even if vultr unblock the port, I think it will be a pain in the future if I setup more mail servers on more VPS's because the time it takes to be checked out by humans and bla bla bla... so, as far, the best  option I've found is hostinger, the cheapest VPS costs $3.5 and doesn't block ports, I asked direct to support.

**Comment by MeliodasZoom** [comment] 2021-12-10 02:26
I have to confirm this for vultr since I have a similar issue. I have made 3 tickets and waited over 48 hours and still no major response. I am still getting automated comments with no major sign of forwarding it to the accounts department.

**Comment by jrejaud** [comment] 2021-12-11 02:06
> I set up vultr specifically for your guide on setting up a website, mailserver, and git server. That is all (though I haven't finished setting up the git server). ![3](https://user-images.githubusercontent.com/71364336/136111428-513aa01a-3650-4219-b52c-e6c396734c97.png) ![2](https://user-images.githubusercontent.com/71364336/136111425-534e0264-07ec-4c82-98cd-69d1e057a466.png) ![1](https://user-images.githubusercontent.com/71364336/136111423-e76aa392-ceb3-4916-9076-8a38d587c411.png)
> 
> Edit: lol, I missed one and doxed myself. Now you can bask in the html on my domain.

They also asked me these questions (name/ org, use case, volume)

I told them what my "legitimate business which is not personal email" does and our "use case which is totally not me sending out personal emails" and like < 100 emails/mo for the vol and they opened the ports rather quickly, less than 12 hours I think. (If these vultures are reading this, in my case it was actually for an actual business mail, do not ban me).

Worst case, just make a basic HTML page with your "business" so that they can open the ports.

**Comment by MeliodasZoom** [comment] 2021-12-12 22:41
Well vultr said they would unblock it but only after a month of use of the vps (not just having an account).

**Comment by jrejaud** [comment] 2021-12-13 01:41
I was using Vultr for ~ 6 months before I decided to use a mailbox server, maybe
that's why they let me slip.
Regardless, this is pretty terrible customer service.
Cheers,Jordan Réjaud  





On Mon, Dec 13, 2021 at 7:41 AM MeliodasZoom ***@***.***>  wrote:


Well vultr said they would unblock it but only after a month of use of the vps
(not just having an account).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android.

**Comment by 258204** [comment] 2021-12-13 06:17
> > I set up vultr specifically for your guide on setting up a website, mailserver, and git server. That is all (though I haven't finished setting up the git server). ![3](https://user-images.githubusercontent.com/71364336/136111428-513aa01a-3650-4219-b52c-e6c396734c97.png) ![2](https://user-images.githubusercontent.com/71364336/136111425-534e0264-07ec-4c82-98cd-69d1e057a466.png) ![1](https://user-images.githubusercontent.com/71364336/136111423-e76aa392-ceb3-4916-9076-8a38d587c411.png)
> > Edit: lol, I missed one and doxed myself. Now you can bask in the html on my domain.
> 
> They also asked me these questions (name/ org, use case, volume)
> 
> I told them what my "legitimate business which is not personal email" does and our "use case which is totally not me sending out personal emails" and like < 100 emails/mo for the vol and they opened the ports rather quickly, less than 12 hours I think. (If these vultures are reading this, in my case it was actually for an actual business mail, do not ban me).
> 
> Worst case, just make a basic HTML page with your "business" so that they can open the ports.

I don't understand why you would make up stories to do business with people who will take 12 hours to do what literally any competitor would do in 5 minutes.

**Comment by MeliodasZoom** [comment] 2021-12-13 06:25
Well sadly I really dont think there are any 

> > > I set up vultr specifically for your guide on setting up a website, mailserver, and git server. That is all (though I haven't finished setting up the git server). ![3](https://user-images.githubusercontent.com/71364336/136111428-513aa01a-3650-4219-b52c-e6c396734c97.png) ![2](https://user-images.githubusercontent.com/71364336/136111425-534e0264-07ec-4c82-98cd-69d1e057a466.png) ![1](https://user-images.githubusercontent.com/71364336/136111423-e76aa392-ceb3-4916-9076-8a38d587c411.png)
> > > Edit: lol, I missed one and doxed myself. Now you can bask in the html on my domain.
> > 
> > 
> > They also asked me these questions (name/ org, use case, volume)
> > I told them what my "legitimate business which is not personal email" does and our "use case which is totally not me sending out personal emails" and like < 100 emails/mo for the vol and they opened the ports rather quickly, less than 12 hours I think. (If these vultures are reading this, in my case it was actually for an actual business mail, do not ban me).
> > Worst case, just make a basic HTML page with your "business" so that they can open the ports.
> 
> I don't understand why you would make up stories to do business with people who will take 12 hours to do what literally any competitor would do in 5 minutes.

well does anyone have any other recommendations? I am thinking of changing from vultr as it took me 4 days to get the reply "wait for one month" which is honestly horrible by any standards.

**Comment by 258204** [comment] 2021-12-13 06:30
@MeliodasZoom  ssdnodes

**Comment by MeliodasZoom** [comment] 2021-12-13 06:31
@258204  thanks will look into it.

**Comment by 258204** [comment] 2021-12-13 06:32
Waiting a month isn't too uncommon, not sure if AWS does it, but I know digital ocean does it. I will say that AWS, digital ocean, linode, etc. will all give you vastly better customer service.

**Comment by adrientremblay** [comment] 2021-12-24 17:28
My account is over a month old I believe. I was having issues with incoming mail, so I created a ticket to unblock port 25. Apparently It was already unblocked on my server for some reason? hmm... The actual problem was I forgot to unblock port 25 on ufw.

The actual reply was very quick, took them 10 minutes to reply. Not sure this issue title is accurate, given they do seem fully willing to unblock the port (given the age of you account is over a month old perhaps)

**Comment by NebulaBC** [comment] 2022-01-18 15:27
I don’t understand why people are using hosts like linode or vultr in the first place. Just use something like Oracle cloud, AWS or Azure. You control the ports yourself, and can open whatever.

**Comment by LukeSmithxyz** [comment] 2022-01-18 15:40
Closing this. I will add a small list of VPS to use, but to be clear (possibly because of this script), Vultr is more wary of opening ports for accounts with less than a month of history.

I will also say, do not host a VPS with Amazon or Microsoft or Oracle. I will assume that was a satirical comment.

**Closed by LukeSmithxyz** 2022-01-18 15:40 UTC

**Comment by vvcares** [comment] 2022-05-11 08:06
No VULTR. Im also having issue with them in the past 1 month, end up they denied to open port. Just used 1st linux VPS. No any bad history with them for my account. But simply they seems dont allow any hosting services mainly for emailing.. Not meant for email marketing..

Simply can say NO TO 'Vultr'
Linode is doing much better in this case..

**Comment by vvcares** [comment] 2022-09-08 02:58
VULTR VPS Linux/ I just installed simple HESTIACP with 1st domain , just to trial purpose. The email sending is blocked by 25 outgoing. They denied to open port. The root emails all are always using port 25, not 587. Even i tried many google search and set to port 587, still no luck. Seems port25 is must for root emails sending to sys admin.

**Comment by Francesco149** [comment] 2022-10-27 00:56
I personally had no problem getting vultr to unblock port 25 (had to wait like 12h though), but I guess they have some criteria for new accounts that charge very little credit because they are likely to abuse it for spam or something.

my reasoning was "personal email server, low volume, sending emails to friends and family". I didn't have a landing page but I did have my email server set up and running, the default nginx landing page and a rainloop instance on a subdomain.

they have a dedicated support form to request smrt port unblock

**Comment by Bernard-Murphy** [comment] 2022-11-04 18:27
Where can I find an updated list or does anyone have any recommendations?

**Comment by diepes** [comment] 2022-12-17 08:41
I tried DigitalOcean not port 25 outbound allowed and no option to open it.

Moved to Vulter.com and they do have a process to request opening port 25.

**Comment by vvcares** [comment] 2022-12-17 08:47
> I tried DigitalOcean not port 25 outbound allowed and no option to open it.
> 
> Moved to Vulter.com and they do have a process to request opening port 25.

DigitalOcean never block port 25. Im using it since 2013. Past 9 years of use, i installed about 50 over Linux hosting servers with them (I did this count for my trial/error projects) with HestiaCP. But the problem is, most of the DO's IPs are blacklisted for emailing. But port 25 still works well.

**Comment by GrenicMars** [comment] 2023-07-08 13:17
> Unless I'm missing something completely here, in which case I apologize in advance, because I'm noway an expert in any of this at all whatsoever, so forgive me if I'm ignorant.
> 
> 
> 
> However, my answer/solution to all of the above woes/problems is as follows:
> 
> 
> 
> never use port 25. I'm not even going to explain why.
> 
> Use port 587, and if you cant(you should be able to MOST of the time), then use port 2525, and if both these ports are not available to you, which would be an almost impossible scenario, then use port 465.
> 
> And if it's the end of the world and none of these 3 ports are available to you, you might as well then resort to using port 25. Oh wait, it's blocked...
> 
> 
> 
> But yea, the above should solve your issues in this thread. 
> 
> If I'm wrong, please forgive my ignorance.
> 
> 
> 
> cheers
> 
> Jerome

**Comment by diepes** [comment] 2023-07-26 01:20
> > I tried DigitalOcean not port 25 outbound allowed and no option to open it.
> > Moved to Vulter.com and they do have a process to request opening port 25.
> 
> Even my website was worked well with DOcean. [Gaushan Roofing Contractor Singapore](https://gaushanconstruction.com.sg/) DigitalOcean never block port 25. Im using it since 2013. Past 9 years of use, i installed about 50 over Linux hosting servers with them (I did this count for my trial/error projects) with HestiaCP. But the problem is, most of the DO's IPs are blacklisted for emailing. But port 25 still works well.

Once you have a fixed IP, with dns and reverse dns setup, you can remove it(the ip) from blacklist sites.   You just have to show that you're the owner takes a day or two.

**Comment by HyderHadi** [comment] 2025-07-15 19:30
I have the same problem :( they refused so hard to open it...

**Comment by diepes** [comment] 2025-07-23 11:16
I have since moved on to https://try.kamatera.com/

**Comment by HyderHadi** [comment] 2025-07-23 20:20
> I have the same problem :( they refused so hard to open it...

I used dartnode eventually, you dont even have to open a ticket to get it to work, it works out of the box... :)

**Comment by sixtymountain** [comment] 2025-12-23 20:05
Can confirm, vultr is a joke.  Have had self-hosted e-mail with unblocked 25 forever, opened a new cloud compute instance, they blocked 25, refuse to unblock, told me to take my business elsewhere.

**Comment by Bernard-Murphy** [comment] 2025-12-23 20:09
They don't really have a choice with new customers or their entire ip block will be blocked by all the major email providers. Why they still deny it to years-long customers who spend hundreds/thousands a month is beyond me.

**Comment by sixtymountain** [comment] 2025-12-23 20:16
unfortunately spent about 5-6 weeks setting up this new server on a new account transferred everything over, moved e-mail as the last task aaand... yup, after weeks of work, found port 25 is blocked and support won't budget despite my old account with them having years and years of history with no abuse.  get to to it all over again.  What are my options for webhosting similar to vultr that actually allows people to run their own mail servers?  I'm not shelling out thousands to have fortune 500 spy on my e-mails, no thank you.

**Comment by vvcares** [comment] 2025-12-24 03:30
Im using Digitalocean (Link: [https://m.do.co/c/935399a19621](https://m.do.co/c/935399a19621)) 
DO + Hestiacp + CSF > for about 12+ years for my 30+ webhosting client.
They allow all ports. Nothing blocked.
Everything works well, BUT, DO IPs are mostly email blacklisted. So im using AWS-SES.
