### ISSUE TITLE
Can not send email to gmail and other emails

### ISSUE THREAD

**Issue by moreravi** [LukeSmithxyz/emailwiz#51] opened 2020-07-09 13:36 UTC
If we create two users on server then they can receive and send emails. Also emails from gmail are receiving. But Can not send email to gmail and other emails. There is problem with opendkim. sudo service opendkim status show red. And in mail.log its showing connection time out. Instance server: aws ec2 ubuntu 18.04

**Comment by themaster567** [comment] 2020-07-11 15:07
I'm having the exact same issue except opendkim shows that it's working fine.

**Comment by Bugswriter** [comment] 2020-07-11 21:55
My thunderbird is showing email sent successfully but I am not receiving on the other end. I can receive email. On evolution I am getting ": Relay access denied”. error.

**Comment by Bugswriter** [comment] 2020-07-11 22:05
Ok it turns out that this relay access denied was just my stupidity I fixed this. 
So basically the problem is .. I am sending email according to email client it's sent successfully, but in I am not receiving on the other end. Not even in spam.

**Comment by themaster567** [comment] 2020-07-11 22:12
> Ok it turns out that this relay access denied was just my stupidity I fixed this.
> So basically the problem is .. I am sending email according to email client it's sent successfully, but in I am not receiving on the other end. Not even in spam.

If you're using Vultr, then I solved this problem by contacting their customer support and asking them to enable SMTP ports. They'll ask you what you intend to use your server for, and just explain to them that you want to use it for a personal email server. I had it resolved within in an hour or so.

**Comment by Bugswriter** [comment] 2020-07-11 22:19
Oh man I was close .. but thanks a lot. Finally I can sleep because of you. I hope they don't take too much time.

**Comment by themaster567** [comment] 2020-07-12 16:42
No problem!

**Comment by riblon** [comment] 2020-07-15 19:45
in vultr....
By default we block SMTP ports on our network to prevent abuse. You can read more about what ports we block here : https://www.vultr.com/docs/what-ports-are-blocked

We will forward this request to our Account Management team for review. Please note the Account Management team's regular hours are 9AM to 5PM US Eastern daily and they will work as swiftly as possible to address your request during that time frame.

**Comment by themaster567** [comment] 2020-07-15 19:47
That's normal. They got back to me after sending that an hour or so later.

**Comment by Bugswriter** [comment] 2020-07-15 20:37
Someone should close this issue. umm @LukeSmithxyz ?

**Comment by tom-lex** [comment] 2020-07-21 01:20
> > Ok it turns out that this relay access denied was just my stupidity I fixed this.
> > So basically the problem is .. I am sending email according to email client it's sent successfully, but in I am not receiving on the other end. Not even in spam.
> 
If you're using Vultr, then I solved this problem by contacting their customer support and asking them to enable SMTP ports. They'll ask you what you intend to use your server for, and just explain to them that you want to use it for a personal email server. I had it resolved within in an hour or so.

Man, thank you for this info! I was losing my mind...

Luke, this is an issue with Vultr for any new server. You may want to update the read me to mention it.

Thank you Luke and all.

**Comment by DJAndries** [comment] 2020-07-21 22:10
Just FYI, set up my server using Luke's vultr referral link, and did not have to request a port 25 unblock. Worked right out of the box. vultr was probably tired of all these requests lol

**Comment by tom-lex** [comment] 2020-07-23 02:29
> Just FYI, set up my server using Luke's vultr referral link, and did not have to request a port 25 unblock. Worked right out of the box. vultr was probably tired of all these requests lol

Ha. Interesting. I'm glad it's working out.

**Comment by minikN** [comment] 2020-08-30 13:23
> Ok it turns out that this relay access denied was just my stupidity I fixed this.
> So basically the problem is .. I am sending email according to email client it's sent successfully, but in I am not receiving on the other end. Not even in spam.

@Bugswriter how did you fix the `Relay access denied` error?

**Comment by portalreaper** [comment] 2020-11-24 23:44
I'm not sending anything. Vultr said they have port 587 open.

**Comment by minikN** [comment] 2020-11-25 19:21
> I'm not sending anything. Vultr said they have port 587 open.

I honestly stopped using this as I've never been able to fix it. I switched to just using mailbox.org. Not advertising this, but you can use it with your own TLD, 0 configuration required apart from DNS records and it's 1€ a month so cheaper than any VPS. I created my account and 15 mins after that I had a working and secure email for my TLD. That's it.

**Comment by portalreaper** [comment] 2020-11-25 19:34
> > I'm not sending anything. Vultr said they have port 587 open.
> 
> I honestly stopped using this as I've never been able to fix it. I switched to just using mailbox.org. Not advertising this, but you can use it with your own TLD, 0 configuration required apart from DNS records and it's 1€ a month so cheaper than any VPS. I created my account and 15 mins after that I had a working and secure email for my TLD. That's it.

I still want to host a VPS for a few other things, but yes, I was definitely thinking about it using a service like that. I've tried to get this working a few times and it's been a complete pain.

**Comment by minikN** [comment] 2020-11-25 19:45
> > > I'm not sending anything. Vultr said they have port 587 open.
> > 
> > 
> > I honestly stopped using this as I've never been able to fix it. I switched to just using mailbox.org. Not advertising this, but you can use it with your own TLD, 0 configuration required apart from DNS records and it's 1€ a month so cheaper than any VPS. I created my account and 15 mins after that I had a working and secure email for my TLD. That's it.
> 
> I still want to host a VPS for a few other things, but yes, I was definitely thinking about it using a service like that. I've tried to get this working a few times and it's been a complete pain.

Well even if want to host a VPS (email and other stuff), I'd still recommend using one VPS just for email as hosting an email service alongside nginx or apache makes things even more complicated. This is also why Luke's script expects a blank system to start off of.

Sure you could host everything on one VPS, but since you (me and many others) weren't even able to get it working on a blank system, I wouldn't even think about getting it to work alongside other things.

Just my opinion after messing with this for a couple of months. Get a VPS and host whatever you want, but use an external and proven service for email. Hurts the geek heart a bit, but at least you got a working mail address.

**Closed** 2020-12-01 00:16 UTC
